struct pixel_in 
{
	float3 color : COLOR0;
	float3 tex1  : TEXCOORD0;
    float3 tex2  : TEXCOORD1;
};

struct pixel_out 
{
	float3 color : COLOR;
};

pixel_out main( pixel_in IN, uniform sampler2D texture1 : TEXUNIT0, uniform sampler2D texture2 : TEXUNIT1 )
{
	pixel_out OUT;

	float3 color1 = tex2D( texture1, IN.tex1 ).rgb;
    float3 color2 = tex2D( texture2, IN.tex2 ).rgb;
	OUT.color = clamp( color2 * color1 * IN.color, 0.0, 1.0 );

	return OUT;
}
